# Generated by Django 5.0.2 on 2024-03-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('ESTRELA', 'Nebulosa'), ('GALAXIA', 'Galaxia'), ('PLANETA', 'Estrela')], default='', max_length=100),
        ),
    ]
